@startuml CHAT REAL TIME

/'----------------------------------------------------------------------
  FORMATAÇÕES GERAIS
  ----------------------------------------------------------------------'/
skinparam diagramBorderColor black
skinparam diagramBorderThickness 3
skinparam participantPadding 20
skinparam defaultFontName helvetica
skinparam defaultFontColor black
skinparam sequenceTitleFontSize 30
skinparam sequenceParticipantBorderColor black
skinparam sequenceParticipantFontSize 14
skinparam actorBackgroundColor transparent
skinparam actorBorderColor black
skinparam actorFontSize 14
skinparam sequenceBoxBorderColor transparent
skinparam sequenceGroupBodyBackgroundColor transparent
skinparam sequenceReferenceBackgroundColor ffffe6
skinparam arrowFontName Courier
skinparam shadowing false
skinparam useBetaStyle true
hide footbox

/'----------------------------------------------------------------------
  PARTICIPANTES
  ----------------------------------------------------------------------'/
box "\nAPI\n" #d3edd6
  participant cli as "Client" #aeeab2
  participant api as "api-ms-chat" #aeeab2
end box
box "\nRecursos\n" #f5e8ba
  participant database as "H2 Database" #f5e5ab
end box

/'----------------------------------------------------------------------
  TITULO
  ----------------------------------------------------------------------'/
title \n\
CHAT REAL TIME \n\
LIST CHATS BY USER

/'----------------------------------------------------------------------
  FLUXO
  ----------------------------------------------------------------------'/

cli -> api ++: \n\
<b>Endpoint</b>: /v1/chats/user/{id} \n\
<b>Method</b>: GET \n\
|||

api -> api: Checks if the users already exists

break#d9d9d9 #f2f2f2 Inconsistent data
|||

api --> cli: \
<b>HTTP 400 (BAD REQUEST)</b> \n\
\n\
{ \n\
    "code": 400, \n\
    "status": "BAD_REQUEST", \n\
    "message": "User does not exists", \n\
    "correlationId": "8b775627-45cb-4bf9-9c41-1e779d95a6c7", \n\
  }
|||
end

api -> database ++: \
\n\
Find all chats by userId
|||

database --> api: \
\n\
Exception
|||

database -> api --: \
\n\
All chats paged and ordered desc by message
|||

api -> cli --: \
\n\
<b>HTTP 200 (OK)</b> \n\
[ \n\
    { \n\
        "chatId": 1, \n\
        "chatName": "Cristhia Dias", \n\
        "message": { \n\
            "lastUser": "Cristhian Dias", \n\
            "lastMessage": "Ok then, see you tomorrow" \n\
        } \n\
    }, \n\
    { \n\
        "chatId": 2, \n\
        "chatName": "Fulano de Tal", \n\
        "toUser": { \n\
            "fullname": "Fulano de Tal" \n\
        }, \n\
        "message": { \n\
            "lastUser": "You", \n\
            "lastMessage": "Are you sure about it?" \n\
        } \n\
    } \n\
] \n\


@enduml